Learning Pandas

In [1]:
import numpy as np
import pandas as pd
import math as m
import statistics as st

How to create a series from a list, numpy array and dict?

In [10]:
#Q1

mylist = list('abcdefghijklmnopqrstuvwxyz')

print(mylist)

myarr = np.arange(1,27)

print(myarr)

mydict = dict(zip(mylist,myarr))

print(mydict)

se = pd.Series(mylist)

print("Series 1")
#print(se)

se = pd.Series(myarr)

print("Series 2")
#print(se)

se = pd.Series(mydict)

print("Series 3")
print(se)

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26]
{'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5, 'f': 6, 'g': 7, 'h': 8, 'i': 9, 'j': 10, 'k': 11, 'l': 12, 'm': 13, 'n': 14, 'o': 15, 'p': 16, 'q': 17, 'r': 18, 's': 19, 't': 20, 'u': 21, 'v': 22, 'w': 23, 'x': 24, 'y': 25, 'z': 26}
Series 1
Series 2
Series 3
a     1
b     2
c     3
d     4
e     5
f     6
g     7
h     8
i     9
j    10
k    11
l    12
m    13
n    14
o    15
p    16
q    17
r    18
s    19
t    20
u    21
v    22
w    23
x    24
y    25
z    26
dtype: int32

How to convert the index of a series into a column of a dataframe?

In [11]:
#Q2
one = pd.DataFrame(se)
print(one)

    0
a   1
b   2
c   3
d   4
e   5
f   6
g   7
h   8
i   9
j  10
k  11
l  12
m  13
n  14
o  15
p  16
q  17
r  18
s  19
t  20
u  21
v  22
w  23
x  24
y  25
z  26

How to combine many series to form a dataframe?

In [12]:
#Q3
ser1 = pd.Series(mylist)
ser2 = pd.Series(myarr)

fser = pd.DataFrame({'col1':ser1,'col2':ser2})

print(fser)

   col1  col2
0     a     1
1     b     2
2     c     3
3     d     4
4     e     5
5     f     6
6     g     7
7     h     8
8     i     9
9     j    10
10    k    11
11    l    12
12    m    13
13    n    14
14    o    15
15    p    16
16    q    17
17    r    18
18    s    19
19    t    20
20    u    21
21    v    22
22    w    23
23    x    24
24    y    25
25    z    26

How to assign name to the seriesâ€™ index?

In [13]:
#Q4
ser = pd.Series(mylist)

ser.name = "column1"

print(ser)

0     a
1     b
2     c
3     d
4     e
5     f
6     g
7     h
8     i
9     j
10    k
11    l
12    m
13    n
14    o
15    p
16    q
17    r
18    s
19    t
20    u
21    v
22    w
23    x
24    y
25    z
Name: column1, dtype: object

How to get the items of series A not present in series B?

In [14]:
#Q5
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

fser = ser1[~ser1.isin(ser2)]

print(fser)

0    1
1    2
2    3
dtype: int64

How to get the items not common to both series A and series B?

In [15]:
#Q6
uni = pd.Series(np.union1d(ser1,ser2))

#print(uni)

inter = pd.Series(np.intersect1d(ser1,ser2))

#print(inter)

uni[~uni.isin(inter)]

0    1
1    2
2    3
5    6
6    7
7    8
dtype: int64

How to get frequency counts of unique items of a series?

In [16]:
#Q7
ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))

s = pd.value_counts(ser)

print(s)

g    6
f    6
h    4
a    4
e    4
b    4
d    2
dtype: int64

How to convert a numpy array to a dataframe of given shape? (L1)

In [17]:
#Q8
ser = pd.Series(np.random.randint(1, 10, 35))

#print(ser)

df = pd.DataFrame(ser.values.reshape(5,7))
print(df)

   0  1  2  3  4  5  6
0  1  8  6  8  3  6  8
1  4  5  8  2  7  5  3
2  5  6  9  8  5  9  8
3  7  5  6  2  8  7  4
4  5  1  2  3  6  2  8

How to find the positions of numbers that are multiples of 3 from a series?

In [18]:
#Q9
ser = pd.Series(np.random.randint(1, 10, 7))
print(ser)

for i in range(len(ser)):
    if (ser[i]%3)==0:
        print(i)

0    3
1    8
2    7
3    7
4    7
5    8
6    1
dtype: int32
0

How to extract items at given positions from a series

In [19]:
#Q10
ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
pos = [0, 4, 8, 14, 20]

for i in pos:
    print(ser[i])

a
e
i
o
u

How to stack two series vertically and horizontally ?

In [20]:
#Q11
ser1 = pd.Series(range(5))
ser2 = pd.Series(list('abcde'))

s = pd.concat([ser1,ser2],axis=1)
print(s)

s = pd.concat([ser1,ser2],axis=0)
print("Hori")
print(s)

   0  1
0  0  a
1  1  b
2  2  c
3  3  d
4  4  e
Hori
0    0
1    1
2    2
3    3
4    4
0    a
1    b
2    c
3    d
4    e
dtype: object

How to get the positions of items of series A in another series B?

In [21]:
#Q12
ser1 = pd.Series([10, 9, 6, 5, 3, 1, 12, 8, 13])
ser2 = pd.Series([1, 3, 10, 13])

for i in range(len(ser1)):
    for j in range(len(ser2)):
        if ser1[i]==ser2[j]:
            print(i)

0
4
5
8

How to compute the mean squared error on a truth and predicted series?
can be done

How to convert the first character of each element in a series to uppercase?

In [22]:
#Q14
ser = pd.Series(['how', 'to', 'kick', 'ass?'])

for i in range(len(ser)):
    print(ser[i].title())

How
To
Kick
Ass?

How to calculate the number of characters in each word in a series?

In [23]:
#Q15
ser = pd.Series(['how', 'to', 'kick', 'ass?'])

for i in range(len(ser)):
    print(len(ser[i]))

3
2
4
4

How to compute difference of differences between consequtive numbers of a series?

In [24]:
#Q16
ser = pd.Series([1, 3, 6, 10, 15, 21, 27, 35])
li = []

for i in range(len(ser)):
    if i==0:
        li.append(ser[i]-0)

    else:
        #print(i-1)
        li.append(ser[i]-ser[i-1])

print(li)

[1, 2, 3, 4, 5, 6, 6, 8]

How to convert a series of date-strings to a timeseries?

In [2]:
#Q17
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])

for i in range(len(ser)):
    print(pd.to_datetime(ser[i]))

print(pd.to_datetime(ser))

2010-01-01 00:00:00
2011-02-02 00:00:00
2012-03-03 00:00:00
2013-04-04 00:00:00
2014-05-05 00:00:00
2015-06-06 12:20:00
0   2010-01-01 00:00:00
1   2011-02-02 00:00:00
2   2012-03-03 00:00:00
3   2013-04-04 00:00:00
4   2014-05-05 00:00:00
5   2015-06-06 12:20:00
dtype: datetime64[ns]

How to filter words that contain atleast 2 vowels from a series?

In [26]:
#Q18
ser = pd.Series(['Apple', 'Orange', 'Plan', 'Python', 'Money'])
#

li = []

def isvow(str):
    return(str.upper() in ['A','E','I','O','U'])

#vow = list('aeiou')


for i in range(len(ser)):
    count = 0
    # print(ser[i])
    for j in range(len(ser[i])):
        # print(ser[i][j])
        if isvow(ser[i][j]):
            count+=1
    li.append(count)

print("Strings with atleast 2 vowels")

for i in range(len(li)):
    if li[i]>=2:
        print(ser[i])

Strings with atleast 2 vowels
Apple
Orange
Money

How to compute the euclidean distance between two series?

In [27]:
#Q19

#formula for disance(square root(summation(square(qi-pi))))

p = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
q = pd.Series([10, 9, 8, 7, 6, 5, 4, 3, 2, 1])

ans = m.sqrt(sum(pow((q-p),2)))

print(ans)

18.16590212458495

How to replace missing spaces in a string with the least frequent character?

In [28]:
#Q20
my_str = 'dbc deb abed gade'
print("Original String\n")
print(my_str,"\n\n")

print("Replaced String\n")

ser = pd.Series(list(my_str))

# print(ser)
li2 = list(ser.value_counts())
li3 = list(ser.unique())
# print(li2)
# print(li3)

max = 0
for i in range(len(li2)):
    if li2[i]>max:
        max = li2[i]

# print(max)
min = max
for i in range(len(li2)):
    if li2[i]<min:
        min = li2[i]
        pos = i

print(my_str.replace(" ",li3[min+1]))


# lis = list(my_str)
# #li2 = []

# print(lis)

# li2 = pd.Series(list(pd.value_counts(lis)))
# li3 = pd.Series(li2)
# print(li2,li3)



# x = my_str.replace(" ",li2[min])
# print(x)

Original String

dbc deb abed gade


Replaced String

dbccdebcabedcgade

How to create a TimeSeries starting â€˜2000-01-01â€™ and 10 weekends (saturdays) after that having random numbers as values?

In [29]:
#Q21
pd.Series(pd.date_range("2000-01-01",periods = 10, freq="W-SAT"),np.arange(10))

0   2000-01-01
1   2000-01-08
2   2000-01-15
3   2000-01-22
4   2000-01-29
5   2000-02-05
6   2000-02-12
7   2000-02-19
8   2000-02-26
9   2000-03-04
dtype: datetime64[ns]

How to import only specified columns from a csv file?

In [30]:
#Q22
filepath = f'E:/Srihari/Python/MDSC-102/22238_Pandas'

df = pd.read_csv(filepath + "/population.csv")

print(df.head())
print("Printing only the column Neigborhood name")
print(df["Neighborhood.Name"])

   Year  District.Code District.Name  Neighborhood.Code  \
0  2017              1  Ciutat Vella                  1
1  2017              1  Ciutat Vella                  2
2  2017              1  Ciutat Vella                  3
3  2017              1  Ciutat Vella                  4
4  2017              2      Eixample                  5

                       Neighborhood.Name Gender  Age  Number
0                               el Raval   Male  0-4     224
1                         el Barri GÃ²tic   Male  0-4      50
2                         la Barceloneta   Male  0-4      43
3  Sant Pere, Santa Caterina i la Ribera   Male  0-4      95
4                          el Fort Pienc   Male  0-4     124
Printing only the column Neigborhood name
0                                            el Raval
1                                      el Barri GÃ²tic
2                                      la Barceloneta
3               Sant Pere, Santa Caterina i la Ribera
4                                       el Fort Pienc
                             ...
70075    Diagonal Mar i el Front MarÃ­tim del Poblenou
70076                           el BesÃ²s i el Maresme
70077                         ProvenÃ§als del Poblenou
70078                        Sant MartÃ­ de ProvenÃ§als
70079                             la Verneda i la Pau
Name: Neighborhood.Name, Length: 70080, dtype: object

How to get the nrows, ncolumns, datatype, summary stats of each column of a dataframe? Also get the array and list equivalent.

In [31]:
#Q23

filepath = f'E:/Srihari/Python/MDSC-102/22238_Pandas'

df = pd.read_csv(filepath + "/population.csv")

print("Number of Rows")
print(df.shape[0],"\n")

print("Number of Columns")
print(df.shape[1],"\n")

print("Data Types of the columns")
print(df.dtypes,"\n")


display(df.describe())
df.values.tolist()

Number of Rows
70080

Number of Columns
8

Data Types of the columns
Year                  int64
District.Code         int64
District.Name        object
Neighborhood.Code     int64
Neighborhood.Name    object
Gender               object
Age                  object
Number                int64
dtype: object

               Year  District.Code  Neighborhood.Code        Number
count  70080.000000   70080.000000       70080.000000  70080.000000
mean    2015.000000       6.246575          37.000000    114.844720
std        1.414224       2.788356          21.071458     96.540389
min     2013.000000       1.000000           1.000000      0.000000
25%     2014.000000       4.000000          19.000000     43.000000
50%     2015.000000       7.000000          37.000000     92.000000
75%     2016.000000       8.000000          55.000000    162.000000
max     2017.000000      10.000000          73.000000    777.000000

[[2017, 1, 'Ciutat Vella', 1, 'el Raval', 'Male', '0-4', 224],
 [2017, 1, 'Ciutat Vella', 2, 'el Barri GÃ²tic', 'Male', '0-4', 50],
 [2017, 1, 'Ciutat Vella', 3, 'la Barceloneta', 'Male', '0-4', 43],
 [2017,
  1,
  'Ciutat Vella',
  4,
  'Sant Pere, Santa Caterina i la Ribera',
  'Male',
  '0-4',
  95],
 [2017, 2, 'Eixample', 5, 'el Fort Pienc', 'Male', '0-4', 124],
 [2017, 2, 'Eixample', 6, 'la Sagrada FamÃ­lia', 'Male', '0-4', 191],
 [2017, 2, 'Eixample', 7, "la Dreta de l'Eixample", 'Male', '0-4', 176],
 [2017,
  2,
  'Eixample',
  8,
  "l'Antiga Esquerra de l'Eixample",
  'Male',
  '0-4',
  158],
 [2017,
  2,
  'Eixample',
  9,
  "la Nova Esquerra de l'Eixample",
  'Male',
  '0-4',
  220],
 [2017, 2, 'Eixample', 10, 'Sant Antoni', 'Male', '0-4', 143],
 [2017, 3, 'Sants-MontjuÃ¯c', 11, 'el Poble Sec', 'Male', '0-4', 180],
 [2017,
  3,
  'Sants-MontjuÃ¯c',
  12,
  'la Marina del Prat Vermell',
  'Male',
  '0-4',
  10],
 [2017, 3, 'Sants-MontjuÃ¯c', 13, 'la Marina de Port', 'Male', '0-4', 124],
 [2017, 3, 'Sants-MontjuÃ¯c', 14, 'la Font de la Guatlla', 'Male', '0-4', 47],
 [2017, 3, 'Sants-MontjuÃ¯c', 15, 'Hostafrancs', 'Male', '0-4', 79],
 [2017, 3, 'Sants-MontjuÃ¯c', 16, 'la Bordeta', 'Male', '0-4', 80],
 [2017, 3, 'Sants-MontjuÃ¯c', 17, 'Sants - Badal', 'Male', '0-4', 84],
 [2017, 3, 'Sants-MontjuÃ¯c', 18, 'Sants', 'Male', '0-4', 195],
 [2017, 4, 'Les Corts', 19, 'les Corts', 'Male', '0-4', 173],
 [2017, 4, 'Les Corts', 20, 'la Maternitat i Sant Ramon', 'Male', '0-4', 85],
 [2017, 4, 'Les Corts', 21, 'Pedralbes', 'Male', '0-4', 37],
 [2017,
  5,
  'SarriÃ -Sant Gervasi',
  22,
  'Vallvidrera, el Tibidabo i les Planes',
  'Male',
  '0-4',
  16],
 [2017, 5, 'SarriÃ -Sant Gervasi', 23, 'SarriÃ ', 'Male', '0-4', 119],
 [2017, 5, 'SarriÃ -Sant Gervasi', 24, 'les Tres Torres', 'Male', '0-4', 71],
 [2017,
  5,
  'SarriÃ -Sant Gervasi',
  25,
  'Sant Gervasi - la Bonanova',
  'Male',
  '0-4',
  104],
 [2017,
  5,
  'SarriÃ -Sant Gervasi',
  26,
  'Sant Gervasi - Galvany',
  'Male',
  '0-4',
  203],
 [2017,
  5,
  'SarriÃ -Sant Gervasi',
  27,
  'el Putxet i el FarrÃ³',
  'Male',
  '0-4',
  150],
 [2017, 6, 'GrÃ cia', 28, 'Vallcarca i els Penitents', 'Male', '0-4', 66],
 [2017, 6, 'GrÃ cia', 29, 'el Coll', 'Male', '0-4', 37],
 [2017, 6, 'GrÃ cia', 30, 'la Salut', 'Male', '0-4', 57],
 [2017, 6, 'GrÃ cia', 31, 'la Vila de GrÃ cia', 'Male', '0-4', 242],
 [2017,
  6,
  'GrÃ cia',
  32,
  "el Camp d'en Grassot i GrÃ cia Nova",
  'Male',
  '0-4',
  168],
 [2017, 7, 'Horta-GuinardÃ³', 33, 'el Baix GuinardÃ³', 'Male', '0-4', 117],
 [2017, 7, 'Horta-GuinardÃ³', 34, 'Can BarÃ³', 'Male', '0-4', 27],
 [2017, 7, 'Horta-GuinardÃ³', 35, 'el GuinardÃ³', 'Male', '0-4', 149],
 [2017, 7, 'Horta-GuinardÃ³', 36, "la Font d'en Fargues", 'Male', '0-4', 36],
 [2017, 7, 'Horta-GuinardÃ³', 37, 'el Carmel', 'Male', '0-4', 147],
 [2017, 7, 'Horta-GuinardÃ³', 38, 'la Teixonera', 'Male', '0-4', 50],
 [2017,
  7,
  'Horta-GuinardÃ³',
  39,
  'Sant GenÃ­s dels Agudells',
  'Male',
  '0-4',
  21],
 [2017, 7, 'Horta-GuinardÃ³', 40, 'Montbau', 'Male', '0-4', 19],
 [2017, 7, 'Horta-GuinardÃ³', 41, "la Vall d'Hebron", 'Male', '0-4', 27],
 [2017, 7, 'Horta-GuinardÃ³', 42, 'la Clota', 'Male', '0-4', 1],
 [2017, 7, 'Horta-GuinardÃ³', 43, 'Horta', 'Male', '0-4', 106],
 [2017,
  8,
  'Nou Barris',
  44,
  'Vilapicina i la Torre Llobeta',
  'Male',
  '0-4',
  85],
 [2017, 8, 'Nou Barris', 45, 'Porta', 'Male', '0-4', 101],
 [2017, 8, 'Nou Barris', 46, 'el TurÃ³ de la Peira', 'Male', '0-4', 68],
 [2017, 8, 'Nou Barris', 47, 'Can Peguera', 'Male', '0-4', 6],
 [2017, 8, 'Nou Barris', 48, 'la Guineueta', 'Male', '0-4', 60],
 [2017, 8, 'Nou Barris', 49, 'Canyelles', 'Male', '0-4', 25],
 [2017, 8, 'Nou Barris', 50, 'les Roquetes', 'Male', '0-4', 80],
 [2017, 8, 'Nou Barris', 51, 'Verdun', 'Male', '0-4', 48],
 [2017, 8, 'Nou Barris', 52, 'la Prosperitat', 'Male', '0-4', 92],
 [2017, 8, 'Nou Barris', 53, 'la Trinitat Nova', 'Male', '0-4', 32],
 [2017, 8, 'Nou Barris', 54, 'Torre BarÃ³', 'Male', '0-4', 12],
 [2017, 8, 'Nou Barris', 55, 'Ciutat Meridiana', 'Male', '0-4', 53],
 [2017, 8, 'Nou Barris', 56, 'Vallbona', 'Male', '0-4', 5],
 [2017, 9, 'Sant Andreu', 57, 'la Trinitat Vella', 'Male', '0-4', 61],
 [2017, 9, 'Sant Andreu', 58, 'BarÃ³ de Viver', 'Male', '0-4', 9],
 [2017, 9, 'Sant Andreu', 59, 'el Bon Pastor', 'Male', '0-4', 55],
 [2017, 9, 'Sant Andreu', 60, 'Sant Andreu', 'Male', '0-4', 261],
 [2017, 9, 'Sant Andreu', 61, 'la Sagrera', 'Male', '0-4', 146],
 [2017, 9, 'Sant Andreu', 62, 'el CongrÃ©s i els Indians', 'Male', '0-4', 62],
 [2017, 9, 'Sant Andreu', 63, 'Navas', 'Male', '0-4', 105],
 [2017,
  10,
  'Sant MartÃ­',
  64,
  "el Camp de l'Arpa del Clot",
  'Male',
  '0-4',
  151],
 [2017, 10, 'Sant MartÃ­', 65, 'el Clot', 'Male', '0-4', 92],
 [2017,
  10,
  'Sant MartÃ­',
  66,
  'el Parc i la Llacuna del Poblenou',
  'Male',
  '0-4',
  70],
 [2017,
  10,
  'Sant MartÃ­',
  67,
  'la Vila OlÃ­mpica del Poblenou',
  'Male',
  '0-4',
  48],
 [2017, 10, 'Sant MartÃ­', 68, 'el Poblenou', 'Male', '0-4', 186],
 [2017,
  10,
  'Sant MartÃ­',
  69,
  'Diagonal Mar i el Front MarÃ­tim del Poblenou',
  'Male',
  '0-4',
  88],
 [2017, 10, 'Sant MartÃ­', 70, 'el BesÃ²s i el Maresme', 'Male', '0-4', 89],
 [2017, 10, 'Sant MartÃ­', 71, 'ProvenÃ§als del Poblenou', 'Male', '0-4', 97],
 [2017, 10, 'Sant MartÃ­', 72, 'Sant MartÃ­ de ProvenÃ§als', 'Male', '0-4', 96],
 [2017, 10, 'Sant MartÃ­', 73, 'la Verneda i la Pau', 'Male', '0-4', 125],
 [2017, 1, 'Ciutat Vella', 1, 'el Raval', 'Male', '0-4', 216],
 [2017, 1, 'Ciutat Vella', 2, 'el Barri GÃ²tic', 'Male', '0-4', 51],
 [2017, 1, 'Ciutat Vella', 3, 'la Barceloneta', 'Male', '0-4', 50],
 [2017,
  1,
  'Ciutat Vella',
  4,
  'Sant Pere, Santa Caterina i la Ribera',
  'Male',
  '0-4',
  88],
 [2017, 2, 'Eixample', 5, 'el Fort Pienc', 'Male', '0-4', 149],
 [2017, 2, 'Eixample', 6, 'la Sagrada FamÃ­lia', 'Male', '0-4', 196],
 [2017, 2, 'Eixample', 7, "la Dreta de l'Eixample", 'Male', '0-4', 213],
 [2017,
  2,
  'Eixample',
  8,
  "l'Antiga Esquerra de l'Eixample",
  'Male',
  '0-4',
  182],
 [2017,
  2,
  'Eixample',
  9,
  "la Nova Esquerra de l'Eixample",
  'Male',
  '0-4',
  229],
 [2017, 2, 'Eixample', 10, 'Sant Antoni', 'Male', '0-4', 175],
 [2017, 3, 'Sants-MontjuÃ¯c', 11, 'el Poble Sec', 'Male', '0-4', 181],
 [2017,
  3,
  'Sants-MontjuÃ¯c',
  12,
  'la Marina del Prat Vermell',
  'Male',
  '0-4',
  6],
 [2017, 3, 'Sants-MontjuÃ¯c', 13, 'la Marina de Port', 'Male', '0-4', 128],
 [2017, 3, 'Sants-MontjuÃ¯c', 14, 'la Font de la Guatlla', 'Male', '0-4', 36],
 [2017, 3, 'Sants-MontjuÃ¯c', 15, 'Hostafrancs', 'Male', '0-4', 47],
 [2017, 3, 'Sants-MontjuÃ¯c', 16, 'la Bordeta', 'Male', '0-4', 77],
 [2017, 3, 'Sants-MontjuÃ¯c', 17, 'Sants - Badal', 'Male', '0-4', 95],
 [2017, 3, 'Sants-MontjuÃ¯c', 18, 'Sants', 'Male', '0-4', 173],
 [2017, 4, 'Les Corts', 19, 'les Corts', 'Male', '0-4', 211],
 [2017, 4, 'Les Corts', 20, 'la Maternitat i Sant Ramon', 'Male', '0-4', 99],
 [2017, 4, 'Les Corts', 21, 'Pedralbes', 'Male', '0-4', 35],
 [2017,
  5,
  'SarriÃ -Sant Gervasi',
  22,
  'Vallvidrera, el Tibidabo i les Planes',
  'Male',
  '0-4',
  37],
 [2017, 5, 'SarriÃ -Sant Gervasi', 23, 'SarriÃ ', 'Male', '0-4', 116],
 [2017, 5, 'SarriÃ -Sant Gervasi', 24, 'les Tres Torres', 'Male', '0-4', 80],
 [2017,
  5,
  'SarriÃ -Sant Gervasi',
  25,
  'Sant Gervasi - la Bonanova',
  'Male',
  '0-4',
  109],
 [2017,
  5,
  'SarriÃ -Sant Gervasi',
  26,
  'Sant Gervasi - Galvany',
  'Male',
  '0-4',
  210],
 [2017,
  5,
  'SarriÃ -Sant Gervasi',
  27,
  'el Putxet i el FarrÃ³',
  'Male',
  '0-4',
  149],
 [2017, 6, 'GrÃ cia', 28, 'Vallcarca i els Penitents', 'Male', '0-4', 70],
 [2017, 6, 'GrÃ cia', 29, 'el Coll', 'Male', '0-4', 37],
 [2017, 6, 'GrÃ cia', 30, 'la Salut', 'Male', '0-4', 39],
 [2017, 6, 'GrÃ cia', 31, 'la Vila de GrÃ cia', 'Male', '0-4', 240],
 [2017,
  6,
  'GrÃ cia',
  32,
  "el Camp d'en Grassot i GrÃ cia Nova",
  'Male',
  '0-4',
  146],
 [2017, 7, 'Horta-GuinardÃ³', 33, 'el Baix GuinardÃ³', 'Male', '0-4', 93],
 [2017, 7, 'Horta-GuinardÃ³', 34, 'Can BarÃ³', 'Male', '0-4', 28],
 [2017, 7, 'Horta-GuinardÃ³', 35, 'el GuinardÃ³', 'Male', '0-4', 184],
 [2017, 7, 'Horta-GuinardÃ³', 36, "la Font d'en Fargues", 'Male', '0-4', 41],
 [2017, 7, 'Horta-GuinardÃ³', 37, 'el Carmel', 'Male', '0-4', 142],
 [2017, 7, 'Horta-GuinardÃ³', 38, 'la Teixonera', 'Male', '0-4', 46],
 [2017,
  7,
  'Horta-GuinardÃ³',
  39,
  'Sant GenÃ­s dels Agudells',
  'Male',
  '0-4',
  18],
 [2017, 7, 'Horta-GuinardÃ³', 40, 'Montbau', 'Male', '0-4', 19],
 [2017, 7, 'Horta-GuinardÃ³', 41, "la Vall d'Hebron", 'Male', '0-4', 28],
 [2017, 7, 'Horta-GuinardÃ³', 42, 'la Clota', 'Male', '0-4', 6],
 [2017, 7, 'Horta-GuinardÃ³', 43, 'Horta', 'Male', '0-4', 105],
 [2017,
  8,
  'Nou Barris',
  44,
  'Vilapicina i la Torre Llobeta',
  'Male',
  '0-4',
  105],
 [2017, 8, 'Nou Barris', 45, 'Porta', 'Male', '0-4', 107],
 [2017, 8, 'Nou Barris', 46, 'el TurÃ³ de la Peira', 'Male', '0-4', 72],
 [2017, 8, 'Nou Barris', 47, 'Can Peguera', 'Male', '0-4', 8],
 [2017, 8, 'Nou Barris', 48, 'la Guineueta', 'Male', '0-4', 64],
 [2017, 8, 'Nou Barris', 49, 'Canyelles', 'Male', '0-4', 32],
 [2017, 8, 'Nou Barris', 50, 'les Roquetes', 'Male', '0-4', 72],
 [2017, 8, 'Nou Barris', 51, 'Verdun', 'Male', '0-4', 54],
 [2017, 8, 'Nou Barris', 52, 'la Prosperitat', 'Male', '0-4', 123],
 [2017, 8, 'Nou Barris', 53, 'la Trinitat Nova', 'Male', '0-4', 43],
 [2017, 8, 'Nou Barris', 54, 'Torre BarÃ³', 'Male', '0-4', 17],
 [2017, 8, 'Nou Barris', 55, 'Ciutat Meridiana', 'Male', '0-4', 67],
 [2017, 8, 'Nou Barris', 56, 'Vallbona', 'Male', '0-4', 6],
 [2017, 9, 'Sant Andreu', 57, 'la Trinitat Vella', 'Male', '0-4', 47],
 [2017, 9, 'Sant Andreu', 58, 'BarÃ³ de Viver', 'Male', '0-4', 16],
 [2017, 9, 'Sant Andreu', 59, 'el Bon Pastor', 'Male', '0-4', 63],
 [2017, 9, 'Sant Andreu', 60, 'Sant Andreu', 'Male', '0-4', 238],
 [2017, 9, 'Sant Andreu', 61, 'la Sagrera', 'Male', '0-4', 133],
 [2017, 9, 'Sant Andreu', 62, 'el CongrÃ©s i els Indians', 'Male', '0-4', 60],
 [2017, 9, 'Sant Andreu', 63, 'Navas', 'Male', '0-4', 94],
 [2017,
  10,
  'Sant MartÃ­',
  64,
  "el Camp de l'Arpa del Clot",
  'Male',
  '0-4',
  159],
 [2017, 10, 'Sant MartÃ­', 65, 'el Clot', 'Male', '0-4', 120],
 [2017,
  10,
  'Sant MartÃ­',
  66,
  'el Parc i la Llacuna del Poblenou',
  'Male',
  '0-4',
  89],
 [2017,
  10,
  'Sant MartÃ­',
  67,
  'la Vila OlÃ­mpica del Poblenou',
  'Male',
  '0-4',
  51],
 [2017, 10, 'Sant MartÃ­', 68, 'el Poblenou', 'Male', '0-4', 171],
 [2017,
  10,
  'Sant MartÃ­',
  69,
  'Diagonal Mar i el Front MarÃ­tim del Poblenou',
  'Male',
  '0-4',
  99],
 [2017, 10, 'Sant MartÃ­', 70, 'el BesÃ²s i el Maresme', 'Male', '0-4', 99],
 [2017, 10, 'Sant MartÃ­', 71, 'ProvenÃ§als del Poblenou', 'Male', '0-4', 97],
 [2017, 10, 'Sant MartÃ­', 72, 'Sant MartÃ­ de ProvenÃ§als', 'Male', '0-4', 93],
 [2017, 10, 'Sant MartÃ­', 73, 'la Verneda i la Pau', 'Male', '0-4', 119],
 [2017, 1, 'Ciutat Vella', 1, 'el Raval', 'Male', '0-4', 213],
 [2017, 1, 'Ciutat Vella', 2, 'el Barri GÃ²tic', 'Male', '0-4', 37],
 [2017, 1, 'Ciutat Vella', 3, 'la Barceloneta', 'Male', '0-4', 39],
 [2017,
  1,
  'Ciutat Vella',
  4,
  'Sant Pere, Santa Caterina i la Ribera',
  'Male',
  '0-4',
  87],
 [2017, 2, 'Eixample', 5, 'el Fort Pienc', 'Male', '0-4', 132],
 [2017, 2, 'Eixample', 6, 'la Sagrada FamÃ­lia', 'Male', '0-4', 193],
 [2017, 2, 'Eixample', 7, "la Dreta de l'Eixample", 'Male', '0-4', 194],
 [2017,
  2,
  'Eixample',
  8,
  "l'Antiga Esquerra de l'Eixample",
  'Male',
  '0-4',
  155],
 [2017,
  2,
  'Eixample',
  9,
  "la Nova Esquerra de l'Eixample",
  'Male',
  '0-4',
  230],
 [2017, 2, 'Eixample', 10, 'Sant Antoni', 'Male', '0-4', 159],
 [2017, 3, 'Sants-MontjuÃ¯c', 11, 'el Poble Sec', 'Male', '0-4', 200],
 [2017,
  3,
  'Sants-MontjuÃ¯c',
  12,
  'la Marina del Prat Vermell',
  'Male',
  '0-4',
  6],
 [2017, 3, 'Sants-MontjuÃ¯c', 13, 'la Marina de Port', 'Male', '0-4', 117],
 [2017, 3, 'Sants-MontjuÃ¯c', 14, 'la Font de la Guatlla', 'Male', '0-4', 38],
 [2017, 3, 'Sants-MontjuÃ¯c', 15, 'Hostafrancs', 'Male', '0-4', 72],
 [2017, 3, 'Sants-MontjuÃ¯c', 16, 'la Bordeta', 'Male', '0-4', 63],
 [2017, 3, 'Sants-MontjuÃ¯c', 17, 'Sants - Badal', 'Male', '0-4', 80],
 [2017, 3, 'Sants-MontjuÃ¯c', 18, 'Sants', 'Male', '0-4', 187],
 [2017, 4, 'Les Corts', 19, 'les Corts', 'Male', '0-4', 190],
 [2017, 4, 'Les Corts', 20, 'la Maternitat i Sant Ramon', 'Male', '0-4', 103],
 [2017, 4, 'Les Corts', 21, 'Pedralbes', 'Male', '0-4', 56],
 [2017,
  5,
  'SarriÃ -Sant Gervasi',
  22,
  'Vallvidrera, el Tibidabo i les Planes',
  'Male',
  '0-4',
  28],
 [2017, 5, 'SarriÃ -Sant Gervasi', 23, 'SarriÃ ', 'Male', '0-4', 172],
 [2017, 5, 'SarriÃ -Sant Gervasi', 24, 'les Tres Torres', 'Male', '0-4', 83],
 [2017,
  5,
  'SarriÃ -Sant Gervasi',
  25,
  'Sant Gervasi - la Bonanova',
  'Male',
  '0-4',
  138],
 [2017,
  5,
  'SarriÃ -Sant Gervasi',
  26,
  'Sant Gervasi - Galvany',
  'Male',
  '0-4',
  180],
 [2017,
  5,
  'SarriÃ -Sant Gervasi',
  27,
  'el Putxet i el FarrÃ³',
  'Male',
  '0-4',
  119],
 [2017, 6, 'GrÃ cia', 28, 'Vallcarca i els Penitents', 'Male', '0-4', 72],
 [2017, 6, 'GrÃ cia', 29, 'el Coll', 'Male', '0-4', 41],
 [2017, 6, 'GrÃ cia', 30, 'la Salut', 'Male', '0-4', 64],
 [2017, 6, 'GrÃ cia', 31, 'la Vila de GrÃ cia', 'Male', '0-4', 226],
 [2017,
  6,
  'GrÃ cia',
  32,
  "el Camp d'en Grassot i GrÃ cia Nova",
  'Male',
  '0-4',
  128],
 [2017, 7, 'Horta-GuinardÃ³', 33, 'el Baix GuinardÃ³', 'Male', '0-4', 92],
 [2017, 7, 'Horta-GuinardÃ³', 34, 'Can BarÃ³', 'Male', '0-4', 26],
 [2017, 7, 'Horta-GuinardÃ³', 35, 'el GuinardÃ³', 'Male', '0-4', 162],
 [2017, 7, 'Horta-GuinardÃ³', 36, "la Font d'en Fargues", 'Male', '0-4', 40],
 [2017, 7, 'Horta-GuinardÃ³', 37, 'el Carmel', 'Male', '0-4', 139],
 [2017, 7, 'Horta-GuinardÃ³', 38, 'la Teixonera', 'Male', '0-4', 50],
 [2017,
  7,
  'Horta-GuinardÃ³',
  39,
  'Sant GenÃ­s dels Agudells',
  'Male',
  '0-4',
  20],
 [2017, 7, 'Horta-GuinardÃ³', 40, 'Montbau', 'Male', '0-4', 14],
 [2017, 7, 'Horta-GuinardÃ³', 41, "la Vall d'Hebron", 'Male', '0-4', 24],
 [2017, 7, 'Horta-GuinardÃ³', 42, 'la Clota', 'Male', '0-4', 9],
 [2017, 7, 'Horta-GuinardÃ³', 43, 'Horta', 'Male', '0-4', 102],
 [2017,
  8,
  'Nou Barris',
  44,
  'Vilapicina i la Torre Llobeta',
  'Male',
  '0-4',
  109],
 [2017, 8, 'Nou Barris', 45, 'Porta', 'Male', '0-4', 117],
 [2017, 8, 'Nou Barris', 46, 'el TurÃ³ de la Peira', 'Male', '0-4', 74],
 [2017, 8, 'Nou Barris', 47, 'Can Peguera', 'Male', '0-4', 4],
 [2017, 8, 'Nou Barris', 48, 'la Guineueta', 'Male', '0-4', 52],
 [2017, 8, 'Nou Barris', 49, 'Canyelles', 'Male', '0-4', 26],
 [2017, 8, 'Nou Barris', 50, 'les Roquetes', 'Male', '0-4', 73],
 [2017, 8, 'Nou Barris', 51, 'Verdun', 'Male', '0-4', 58],
 [2017, 8, 'Nou Barris', 52, 'la Prosperitat', 'Male', '0-4', 110],
 [2017, 8, 'Nou Barris', 53, 'la Trinitat Nova', 'Male', '0-4', 33],
 [2017, 8, 'Nou Barris', 54, 'Torre BarÃ³', 'Male', '0-4', 15],
 [2017, 8, 'Nou Barris', 55, 'Ciutat Meridiana', 'Male', '0-4', 56],
 [2017, 8, 'Nou Barris', 56, 'Vallbona', 'Male', '0-4', 11],
 [2017, 9, 'Sant Andreu', 57, 'la Trinitat Vella', 'Male', '0-4', 68],
 [2017, 9, 'Sant Andreu', 58, 'BarÃ³ de Viver', 'Male', '0-4', 12],
 [2017, 9, 'Sant Andreu', 59, 'el Bon Pastor', 'Male', '0-4', 80],
 [2017, 9, 'Sant Andreu', 60, 'Sant Andreu', 'Male', '0-4', 281],
 [2017, 9, 'Sant Andreu', 61, 'la Sagrera', 'Male', '0-4', 144],
 [2017, 9, 'Sant Andreu', 62, 'el CongrÃ©s i els Indians', 'Male', '0-4', 72],
 [2017, 9, 'Sant Andreu', 63, 'Navas', 'Male', '0-4', 89],
 [2017,
  10,
  'Sant MartÃ­',
  64,
  "el Camp de l'Arpa del Clot",
  'Male',
  '0-4',
  130],
 [2017, 10, 'Sant MartÃ­', 65, 'el Clot', 'Male', '0-4', 98],
 [2017,
  10,
  'Sant MartÃ­',
  66,
  'el Parc i la Llacuna del Poblenou',
  'Male',
  '0-4',
  72],
 [2017,
  10,
  'Sant MartÃ­',
  67,
  'la Vila OlÃ­mpica del Poblenou',
  'Male',
  '0-4',
  55],
 [2017, 10, 'Sant MartÃ­', 68, 'el Poblenou', 'Male', '0-4', 202],
 [2017,
  10,
  'Sant MartÃ­',
  69,
  'Diagonal Mar i el Front MarÃ­tim del Poblenou',
  'Male',
  '0-4',
  93],
 [2017, 10, 'Sant MartÃ­', 70, 'el BesÃ²s i el Maresme', 'Male', '0-4', 129],
 [2017, 10, 'Sant MartÃ­', 71, 'ProvenÃ§als del Poblenou', 'Male', '0-4', 98],
 [2017, 10, 'Sant MartÃ­', 72, 'Sant MartÃ­ de ProvenÃ§als', 'Male', '0-4', 100],
 [2017, 10, 'Sant MartÃ­', 73, 'la Verneda i la Pau', 'Male', '0-4', 98],
 [2017, 1, 'Ciutat Vella', 1, 'el Raval', 'Male', '0-4', 198],
 [2017, 1, 'Ciutat Vella', 2, 'el Barri GÃ²tic', 'Male', '0-4', 51],
 [2017, 1, 'Ciutat Vella', 3, 'la Barceloneta', 'Male', '0-4', 48],
 [2017,
  1,
  'Ciutat Vella',
  4,
  'Sant Pere, Santa Caterina i la Ribera',
  'Male',
  '0-4',
  82],
 [2017, 2, 'Eixample', 5, 'el Fort Pienc', 'Male', '0-4', 107],
 [2017, 2, 'Eixample', 6, 'la Sagrada FamÃ­lia', 'Male', '0-4', 171],
 [2017, 2, 'Eixample', 7, "la Dreta de l'Eixample", 'Male', '0-4', 198],
 [2017,
  2,
  'Eixample',
  8,
  "l'Antiga Esquerra de l'Eixample",
  'Male',
  '0-4',
  156],
 [2017,
  2,
  'Eixample',
  9,
  "la Nova Esquerra de l'Eixample",
  'Male',
  '0-4',
  204],
 [2017, 2, 'Eixample', 10, 'Sant Antoni', 'Male', '0-4', 168],
 [2017, 3, 'Sants-MontjuÃ¯c', 11, 'el Poble Sec', 'Male', '0-4', 179],
 [2017,
  3,
  'Sants-MontjuÃ¯c',
  12,
  'la Marina del Prat Vermell',
  'Male',
  '0-4',
  8],
 [2017, 3, 'Sants-MontjuÃ¯c', 13, 'la Marina de Port', 'Male', '0-4', 122],
 [2017, 3, 'Sants-MontjuÃ¯c', 14, 'la Font de la Guatlla', 'Male', '0-4', 33],
 [2017, 3, 'Sants-MontjuÃ¯c', 15, 'Hostafrancs', 'Male', '0-4', 75],
 [2017, 3, 'Sants-MontjuÃ¯c', 16, 'la Bordeta', 'Male', '0-4', 70],
 [2017, 3, 'Sants-MontjuÃ¯c', 17, 'Sants - Badal', 'Male', '0-4', 83],
 [2017, 3, 'Sants-MontjuÃ¯c', 18, 'Sants', 'Male', '0-4', 168],
 [2017, 4, 'Les Corts', 19, 'les Corts', 'Male', '0-4', 196],
 [2017, 4, 'Les Corts', 20, 'la Maternitat i Sant Ramon', 'Male', '0-4', 108],
 [2017, 4, 'Les Corts', 21, 'Pedralbes', 'Male', '0-4', 45],
 [2017,
  5,
  'SarriÃ -Sant Gervasi',
  22,
  'Vallvidrera, el Tibidabo i les Planes',
  'Male',
  '0-4',
  40],
 [2017, 5, 'SarriÃ -Sant Gervasi', 23, 'SarriÃ ', 'Male', '0-4', 152],
 [2017, 5, 'SarriÃ -Sant Gervasi', 24, 'les Tres Torres', 'Male', '0-4', 95],
 [2017,
  5,
  'SarriÃ -Sant Gervasi',
  25,
  'Sant Gervasi - la Bonanova',
  'Male',
  '0-4',
  130],
 [2017,
  5,
  'SarriÃ -Sant Gervasi',
  26,
  'Sant Gervasi - Galvany',
  'Male',
  '0-4',
  204],
 [2017,
  5,
  'SarriÃ -Sant Gervasi',
  27,
  'el Putxet i el FarrÃ³',
  'Male',
  '0-4',
  134],
 [2017, 6, 'GrÃ cia', 28, 'Vallcarca i els Penitents', 'Male', '0-4', 68],
 [2017, 6, 'GrÃ cia', 29, 'el Coll', 'Male', '0-4', 36],
 [2017, 6, 'GrÃ cia', 30, 'la Salut', 'Male', '0-4', 63],
 [2017, 6, 'GrÃ cia', 31, 'la Vila de GrÃ cia', 'Male', '0-4', 219],
 [2017,
  6,
  'GrÃ cia',
  32,
  "el Camp d'en Grassot i GrÃ cia Nova",
  'Male',
  '0-4',
  148],
 [2017, 7, 'Horta-GuinardÃ³', 33, 'el Baix GuinardÃ³', 'Male', '0-4', 90],
 [2017, 7, 'Horta-GuinardÃ³', 34, 'Can BarÃ³', 'Male', '0-4', 25],
 [2017, 7, 'Horta-GuinardÃ³', 35, 'el GuinardÃ³', 'Male', '0-4', 148],
 [2017, 7, 'Horta-GuinardÃ³', 36, "la Font d'en Fargues", 'Male', '0-4', 32],
 [2017, 7, 'Horta-GuinardÃ³', 37, 'el Carmel', 'Male', '0-4', 131],
 [2017, 7, 'Horta-GuinardÃ³', 38, 'la Teixonera', 'Male', '0-4', 52],
 [2017,
  7,
  'Horta-GuinardÃ³',
  39,
  'Sant GenÃ­s dels Agudells',
  'Male',
  '0-4',
  37],
 [2017, 7, 'Horta-GuinardÃ³', 40, 'Montbau', 'Male', '0-4', 9],
 [2017, 7, 'Horta-GuinardÃ³', 41, "la Vall d'Hebron", 'Male', '0-4', 32],
 [2017, 7, 'Horta-GuinardÃ³', 42, 'la Clota', 'Male', '0-4', 7],
 [2017, 7, 'Horta-GuinardÃ³', 43, 'Horta', 'Male', '0-4', 118],
 [2017,
  8,
  'Nou Barris',
  44,
  'Vilapicina i la Torre Llobeta',
  'Male',
  '0-4',
  104],
 [2017, 8, 'Nou Barris', 45, 'Porta', 'Male', '0-4', 112],
 [2017, 8, 'Nou Barris', 46, 'el TurÃ³ de la Peira', 'Male', '0-4', 72],

How to get the mean of a series grouped by another series?

In [32]:
#Q24

fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))
print(weights.tolist())
print(fruit.tolist())

# a = [1,2,3,4]
# print(a)
# print(st.mean(a))
fru = fruit.tolist()
wei  = weights.tolist()

mean = (weights.groupby(fruit)).mean()
print(mean)

[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]
['banana', 'carrot', 'carrot', 'banana', 'apple', 'banana', 'carrot', 'apple', 'apple', 'banana']
apple     7.333333
banana    5.250000
carrot    4.000000
dtype: float64

How to import only every nth row from a csv file to create a dataframe?

In [4]:
#Q25

rn = int(input("Enter the nth row number to display : "))

filepath = f'E:/Srihari/Python/MDSC-102/22238_Pandas'

df = pd.read_csv(filepath + "/population.csv",nrows=rn*20+1)


for i in range(1,len(df)+1):
    if i%rn==0:
        display(df.iloc[i])

Year                                                  2017
District.Code                                            1
District.Name                                 Ciutat Vella
Neighborhood.Code                                        4
Neighborhood.Name    Sant Pere, Santa Caterina i la Ribera
Gender                                                Male
Age                                                    0-4
Number                                                  95
Name: 3, dtype: object

Year                                   2017
District.Code                             2
District.Name                      Eixample
Neighborhood.Code                         7
Neighborhood.Name    la Dreta de l'Eixample
Gender                                 Male
Age                                     0-4
Number                                  176
Name: 6, dtype: object

Year                        2017
District.Code                  2
District.Name           Eixample
Neighborhood.Code             10
Neighborhood.Name    Sant Antoni
Gender                      Male
Age                          0-4
Number                       143
Name: 9, dtype: object

Year                              2017
District.Code                        3
District.Name           Sants-MontjuÃ¯c
Neighborhood.Code                   13
Neighborhood.Name    la Marina de Port
Gender                            Male
Age                                0-4
Number                             124
Name: 12, dtype: object

Year                           2017
District.Code                     3
District.Name        Sants-MontjuÃ¯c
Neighborhood.Code                16
Neighborhood.Name        la Bordeta
Gender                         Male
Age                             0-4
Number                           80
Name: 15, dtype: object

Year                      2017
District.Code                4
District.Name        Les Corts
Neighborhood.Code           19
Neighborhood.Name    les Corts
Gender                    Male
Age                        0-4
Number                     173
Name: 18, dtype: object

Year                                                  2017
District.Code                                            5
District.Name                          SarriÃ -Sant Gervasi
Neighborhood.Code                                       22
Neighborhood.Name    Vallvidrera, el Tibidabo i les Planes
Gender                                                Male
Age                                                    0-4
Number                                                  16
Name: 21, dtype: object

Year                                       2017
District.Code                                 5
District.Name               SarriÃ -Sant Gervasi
Neighborhood.Code                            25
Neighborhood.Name    Sant Gervasi - la Bonanova
Gender                                     Male
Age                                         0-4
Number                                      104
Name: 24, dtype: object

Year                                      2017
District.Code                                6
District.Name                           GrÃ cia
Neighborhood.Code                           28
Neighborhood.Name    Vallcarca i els Penitents
Gender                                    Male
Age                                        0-4
Number                                      66
Name: 27, dtype: object

Year                              2017
District.Code                        6
District.Name                   GrÃ cia
Neighborhood.Code                   31
Neighborhood.Name    la Vila de GrÃ cia
Gender                            Male
Age                                0-4
Number                             242
Name: 30, dtype: object

Year                           2017
District.Code                     7
District.Name        Horta-GuinardÃ³
Neighborhood.Code                34
Neighborhood.Name          Can BarÃ³
Gender                         Male
Age                             0-4
Number                           27
Name: 33, dtype: object

Year                           2017
District.Code                     7
District.Name        Horta-GuinardÃ³
Neighborhood.Code                37
Neighborhood.Name         el Carmel
Gender                         Male
Age                             0-4
Number                          147
Name: 36, dtype: object

Year                           2017
District.Code                     7
District.Name        Horta-GuinardÃ³
Neighborhood.Code                40
Neighborhood.Name           Montbau
Gender                         Male
Age                             0-4
Number                           19
Name: 39, dtype: object

Year                           2017
District.Code                     7
District.Name        Horta-GuinardÃ³
Neighborhood.Code                43
Neighborhood.Name             Horta
Gender                         Male
Age                             0-4
Number                          106
Name: 42, dtype: object

Year                                2017
District.Code                          8
District.Name                 Nou Barris
Neighborhood.Code                     46
Neighborhood.Name    el TurÃ³ de la Peira
Gender                              Male
Age                                  0-4
Number                                68
Name: 45, dtype: object

Year                       2017
District.Code                 8
District.Name        Nou Barris
Neighborhood.Code            49
Neighborhood.Name     Canyelles
Gender                     Male
Age                         0-4
Number                       25
Name: 48, dtype: object

Year                           2017
District.Code                     8
District.Name            Nou Barris
Neighborhood.Code                52
Neighborhood.Name    la Prosperitat
Gender                         Male
Age                             0-4
Number                           92
Name: 51, dtype: object

Year                             2017
District.Code                       8
District.Name              Nou Barris
Neighborhood.Code                  55
Neighborhood.Name    Ciutat Meridiana
Gender                           Male
Age                               0-4
Number                             53
Name: 54, dtype: object

Year                          2017
District.Code                    9
District.Name          Sant Andreu
Neighborhood.Code               58
Neighborhood.Name    BarÃ³ de Viver
Gender                        Male
Age                            0-4
Number                           9
Name: 57, dtype: object

Year                        2017
District.Code                  9
District.Name        Sant Andreu
Neighborhood.Code             61
Neighborhood.Name     la Sagrera
Gender                      Male
Age                          0-4
Number                       146
Name: 60, dtype: object

How to rename a specific columns in a dataframe?

In [14]:
#Q26

filepath = f'E:/Srihari/Python/MDSC-102/22238_Pandas'

df = pd.read_csv(filepath + "/population.csv")
display(df.head())

print("The dot in the column name is removed")
df = df.rename(columns= {"District.Code":"District Code", "District.Name":"District Name", "Neighborhood.Code" : "Neighborhood Code", "Neighborhood.Name": "Neighborhood Name"})
display(df.head())

,Year,District.Code,District.Name,Neighborhood.Code,Neighborhood.Name,Gender,Age,Number
0,2017,1,Ciutat Vella,1,el Raval,Male,0-4,224
1,2017,1,Ciutat Vella,2,el Barri GÃ²tic,Male,0-4,50
2,2017,1,Ciutat Vella,3,la Barceloneta,Male,0-4,43
3,2017,1,Ciutat Vella,4,"Sant Pere, Santa Caterina i la Ribera",Male,0-4,95
4,2017,2,Eixample,5,el Fort Pienc,Male,0-4,124

The dot in the column name is removed

,Year,District Code,District Name,Neighborhood Code,Neighborhood Name,Gender,Age,Number
0,2017,1,Ciutat Vella,1,el Raval,Male,0-4,224
1,2017,1,Ciutat Vella,2,el Barri GÃ²tic,Male,0-4,50
2,2017,1,Ciutat Vella,3,la Barceloneta,Male,0-4,43
3,2017,1,Ciutat Vella,4,"Sant Pere, Santa Caterina i la Ribera",Male,0-4,95
4,2017,2,Eixample,5,el Fort Pienc,Male,0-4,124

How to check if a dataframe has any missing values?

In [15]:
#Q27

filepath = f'E:/Srihari/Python/MDSC-102/22238_Pandas'

df = pd.read_csv(filepath + "/population.csv")
display(df.head())

df.isnull().values.any()

,Year,District.Code,District.Name,Neighborhood.Code,Neighborhood.Name,Gender,Age,Number
0,2017,1,Ciutat Vella,1,el Raval,Male,0-4,224
1,2017,1,Ciutat Vella,2,el Barri GÃ²tic,Male,0-4,50
2,2017,1,Ciutat Vella,3,la Barceloneta,Male,0-4,43
3,2017,1,Ciutat Vella,4,"Sant Pere, Santa Caterina i la Ribera",Male,0-4,95
4,2017,2,Eixample,5,el Fort Pienc,Male,0-4,124

False

How to count the number of missing values in each column?

In [23]:
#Q28

filepath = f'E:/Srihari/Python/MDSC-102/22238_Pandas'

df = pd.read_csv(filepath + "/population.csv")

(df.columns.isnull())

array([False, False, False, False, False, False, False, False])

How to select a specific column from a dataframe as a dataframe instead of a series?

In [31]:
#Q29

df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))
display(df)

df1 = pd.DataFrame(index=df['a'])
display(df1)

    a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19

Empty DataFrame
Columns: []
Index: [0, 5, 10, 15]

How to change the order of columns of a dataframe?

In [ ]:
#Q30

df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))

df1 = pd.DataFrame()

How to set the number of rows and columns displayed in the output?

In [40]:
#Q31

filepath = f'E:/Srihari/Python/MDSC-102/22238_Pandas'

df = pd.read_csv(filepath + "/population.csv")

pd.set_option("display.max_rows",10)
pd.set_option("display.max_columns",10)
display(df)
#pd.describe_option()

,Year,District.Code,District.Name,Neighborhood.Code,Neighborhood.Name,Gender,Age,Number
0,2017,1,Ciutat Vella,1,el Raval,Male,0-4,224
1,2017,1,Ciutat Vella,2,el Barri GÃ²tic,Male,0-4,50
2,2017,1,Ciutat Vella,3,la Barceloneta,Male,0-4,43
3,2017,1,Ciutat Vella,4,"Sant Pere, Santa Caterina i la Ribera",Male,0-4,95
4,2017,2,Eixample,5,el Fort Pienc,Male,0-4,124
...,...,...,...,...,...,...,...,...
70075,2013,10,Sant MartÃ­,69,Diagonal Mar i el Front MarÃ­tim del Poblenou,Female,>=95,21
70076,2013,10,Sant MartÃ­,70,el BesÃ²s i el Maresme,Female,>=95,25
70077,2013,10,Sant MartÃ­,71,ProvenÃ§als del Poblenou,Female,>=95,31
70078,2013,10,Sant MartÃ­,72,Sant MartÃ­ de ProvenÃ§als,Female,>=95,38
70079,2013,10,Sant MartÃ­,73,la Verneda i la Pau,Female,>=95,47

How to format all the values in a dataframe as percentages?

In [45]:
#Q32

df = pd.DataFrame(np.random.random(4), columns=['random'])
df
df.style.format({
    'random': '{0:.2%}'.format})

How to find the position of the nth largest value greater than a given value?

In ser, find the position of the 2nd largest value greater than the mean.

In [72]:
#Q33

ser = pd.Series(np.random.randint(1, 100, 15))

li = ser.tolist()
print(li)

mean = ser.mean()
print("Mean of the Series")
print(round(mean))

np.argwhere(li > mean)[1]

[90, 46, 30, 28, 2, 92, 33, 73, 62, 36, 21, 98, 97, 81, 3]
Mean of the Series
53

array([5], dtype=int64)

How to swap two rows of a dataframe?

In [75]:
#Q34

df = pd.DataFrame(np.arange(25).reshape(5, -1))

def sr(df, i, j):
    x, y = df.iloc[i, :].copy(), df.iloc[j, :].copy()
    df.iloc[i, :], df.iloc[j, :] = y, x
    return df

print(sr(df, 1, 2))

    0   1   2   3   4
0   0   1   2   3   4
1  10  11  12  13  14
2   5   6   7   8   9
3  15  16  17  18  19
4  20  21  22  23  24

How to reverse the rows of a dataframe?

In [76]:
#Q35

df = pd.DataFrame(np.arange(25).reshape(5, -1))

df.iloc[::-1, :]

    0   1   2   3   4
4  20  21  22  23  24
3  15  16  17  18  19
2  10  11  12  13  14
1   5   6   7   8   9
0   0   1   2   3   4

Which column contains the highest number of row-wise maximum values?

In [77]:
#Q36

df = pd.DataFrame(np.random.randint(1,100, 40).reshape(10, -1))



print(df.apply(np.argmax, axis=1).value_counts().index[0])

2

How to know the maximum possible correlation value of each column against other columns?

In [79]:
#Q37

df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1), columns=list('pqrstuvwxy'), index=list('abcdefgh'))

abs = np.abs(df.corr())
mc = abs.apply(lambda x: sorted(x)[-2])
print('Maximum Correlation : ', np.round(mc.tolist(), 2))

Maximum Correlation :  [0.74 0.56 0.71 0.71 0.5  0.6  0.56 0.74 0.56 0.54]

How to create a column that contains the penultimate value in each row?

In [80]:
#Q38

df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))

out = df.apply(lambda x: x.sort_values().unique()[-2], axis=1)
df['penultimate'] = out
print(df)

    0   1   2   3   4  ...   6   7   8   9  penultimate
0  50   4   9  93  12  ...  40  90  83  21           90
1  18   4  67  12  16  ...  27  20  69  24           67
2  19  58  45  19  34  ...  50   4  73  34           58
3  22  75  66  66  16  ...  33  90  86  80           86
4  73  49  94  47  96  ...  63  86  16  57           94
5  56  91  69  60  70  ...  33  81  52  32           81
6  92  47  66  61  88  ...   8  90   4   1           90
7  58  49  21  98  52  ...  52  44   3  59           59

[8 rows x 11 columns]

Normalize all columns of df by subtracting the column mean and divide by standard deviation.
Range all columns of df such that the minimum value in each column is 0 and max is 1.

In [81]:
#Q39

df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))

out1 = df.apply(lambda x: ((x - x.mean())/x.std()).round(2))
print('1 \n',out1)

out2 = df.apply(lambda x: ((x.max() - x)/(x.max() - x.min())).round(2))
print('2\n', out2)

1
       0     1     2     3     4     5     6     7     8     9
0 -1.29 -0.60 -0.23  0.09  0.29  0.68  0.92  1.98  0.72 -1.30
1  1.04  0.58  0.30  0.94 -0.73 -0.86  0.83 -0.99  1.05  1.22
2 -1.52  1.36 -0.99  0.73  0.98  1.55 -0.25  0.53 -1.35  0.82
3  0.21  0.50  0.98 -1.68 -0.37  1.02 -0.59 -0.92 -1.20 -1.41
4  0.85 -0.63 -0.51  0.87  0.59  0.05  0.27  0.08  0.72  0.88
5  1.04 -1.88 -0.47  0.70 -1.56 -0.32 -1.79 -0.67  0.88  0.05
6 -0.35  0.50 -0.95 -0.58  1.45 -1.14 -0.59 -0.50 -0.90  0.30
7  0.02  0.19  1.87 -1.08 -0.64 -0.98  1.20  0.50  0.07 -0.55
2
       0     1     2     3     4     5     6     7     8     9
0  0.91  0.60  0.73  0.32  0.38  0.33  0.09  0.00  0.14  0.96
1  0.00  0.24  0.55  0.00  0.73  0.90  0.12  1.00  0.00  0.00
2  1.00  0.00  1.00  0.08  0.15  0.00  0.48  0.49  1.00  0.15
3  0.32  0.27  0.31  1.00  0.60  0.20  0.60  0.98  0.94  1.00
4  0.07  0.61  0.83  0.03  0.29  0.56  0.31  0.64  0.14  0.13
5  0.00  1.00  0.82  0.09  1.00  0.70  1.00  0.89  0.07  0.45
6  0.54  0.27  0.99  0.58  0.00  1.00  0.60  0.84  0.81  0.35
7  0.40  0.36  0.00  0.77  0.69  0.94  0.00  0.50  0.41  0.67

How to compute the correlation of each row with the suceeding row?

In [83]:
#Q40

df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))

[df.iloc[i].corr(df.iloc[i+1]).round(2) for i in range(df.shape[0])[:-1]]

[-0.24, -0.1, -0.0, 0.16, -0.11, 0.03, 0.2]

How to replace both the diagonals of dataframe with 0?

In [85]:
#Q40

df = pd.DataFrame(np.random.randint(1,100, 100).reshape(10, -1))

for i in range(df.shape[0]):
    df.iat[i, i] = 0
    df.iat[df.shape[0]-i-1, i] = 0

display(df)

    0   1   2   3   4   5   6   7   8   9
0   0   1  69  65  43  70  69  77  80   0
1  99   0  90  12  60  26  91  26   0  92
2   7  92   0  80  16  81  15   0  91  68
3  28   9  32   0  68  55   0  89  40  36
4  64  66  61  80   0   0  21  14  73   2
5  94  64  83  61   0   0  16   5  44  84
6  76  38  52   0  41  56   0  31  44  18
7  27  90   0  66  31  99  50   0  33  98
8  64   0  22  21  46  65  96  14   0  40
9   0  30  54  28   5  31  57  16  42   0

How to get the particular group of a groupby dataframe by key?

In [86]:
#Q41

df = pd.DataFrame({'col1': ['apple', 'banana', 'orange'] * 3,
                   'col2': np.random.rand(9),
                   'col3': np.random.randint(0, 15, 9)})

df_grouped = df.groupby(['col1'])

df_grouped.get_group('apple')

    col1      col2  col3
0  apple  0.114711    12
3  apple  0.756685    11
6  apple  0.959934    14

How to get the nâ€™th largest value of a column when grouped by another column?

In [88]:
#Q42

df = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                   'taste': np.random.rand(9),
                   'price': np.random.randint(0, 15, 9)})


df_grpd = df['taste'].groupby(df.fruit)
df_grpd.get_group('banana').sort_values().iloc[-2]

0.43476993440819467

 How to compute grouped mean on pandas dataframe and keep the grouped column as another column (not index)?

In [89]:
#Q43

df = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                   'rating': np.random.rand(9),
                   'price': np.random.randint(0, 15, 9)})


out = df.groupby('fruit', as_index=False)['price'].mean()
print(out)

    fruit     price
0   apple  8.333333
1  banana  5.000000
2  orange  9.333333

How to join two dataframes by 2 columns so they have only the common rows?

In [91]:
#Q44

df1 = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                    'weight': ['high', 'medium', 'low'] * 3,
                    'price': np.random.randint(0, 15, 9)})

df2 = pd.DataFrame({'pazham': ['apple', 'orange', 'pine'] * 2,
                    'kilo': ['high', 'low'] * 3,
                    'price': np.random.randint(0, 15, 6)})


pd.merge(df1, df2, how='inner', left_on=['fruit', 'weight'], right_on=['pazham', 'kilo'], suffixes=['_left', '_right'])

    fruit weight  price_left  pazham  kilo  price_right
0   apple   high          14   apple  high            0
1   apple   high          10   apple  high            0
2   apple   high           5   apple  high            0
3  orange    low           7  orange   low            5
4  orange    low          14  orange   low            5
5  orange    low           8  orange   low            5

How to remove rows from a dataframe that are present in another dataframe?

In [92]:
#Q45

df1 = pd.DataFrame({'fruit': ['apple', 'orange', 'banana'] * 3,
                    'weight': ['high', 'medium', 'low'] * 3,
                    'price': np.arange(9)})

df2 = pd.DataFrame({'fruit': ['apple', 'orange', 'pine'] * 2,
                    'weight': ['high', 'medium'] * 3,
                    'price': np.arange(6)})


print(df1[~df1.isin(df2).all(1)])

    fruit  weight  price
2  banana     low      2
3   apple    high      3
4  orange  medium      4
5  banana     low      5
6   apple    high      6
7  orange  medium      7
8  banana     low      8

How to get the positions where values of two columns match?

In [93]:
#Q46

df = pd.DataFrame({'fruit1': np.random.choice(['apple', 'orange', 'banana'], 10),
                    'fruit2': np.random.choice(['apple', 'orange', 'banana'], 10)})

np.where(df.fruit1 == df.fruit2)

(array([3, 6, 7, 8, 9], dtype=int64),)

How to get the frequency of unique values in the entire dataframe?

In [95]:
#Q47

df = pd.DataFrame(np.random.randint(1, 10, 20).reshape(-1, 4), columns = list('abcd'))

pd.value_counts(df.values.ravel())

1    4
4    4
9    4
5    2
3    2
8    2
2    1
7    1
dtype: int64

How to split a text column into two separate columns?

In [97]:
#Q48

df = pd.DataFrame(["STD, City    State",
"33, Kolkata    West Bengal",
"44, Chennai    Tamil Nadu",
"40, Hyderabad    Telengana",
"80, Bangalore    Karnataka"], columns=['row'])


df_out = df.row.str.split(',|\t', expand=True)

new_header = df_out.iloc[0]
df_out = df_out[1:]
df_out.columns = new_header
print(df_out)

0 STD            City    State
1  33   Kolkata    West Bengal
2  44    Chennai    Tamil Nadu
3  40   Hyderabad    Telengana
4  80   Bangalore    Karnataka

How to create one-hot encodings of a categorical variable (dummy variables)?

In [98]:
#Q49

df = pd.DataFrame(np.arange(25).reshape(5,-1), columns=list('abcde'))

df_onehot = pd.concat([pd.get_dummies(df['a']), df[list('bcde')]], axis=1)
print(df_onehot)

   0  5  10  15  20   b   c   d   e
0  1  0   0   0   0   1   2   3   4
1  0  1   0   0   0   6   7   8   9
2  0  0   1   0   0  11  12  13  14
3  0  0   0   1   0  16  17  18  19
4  0  0   0   0   1  21  22  23  24

How to get the last n rows of a dataframe with row sum > 100?

In [100]:
#Q50

df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

rowsums = df.apply(np.sum, axis=1)

last_two_rows = df.iloc[np.where(rowsums > 100)[0][-2:], :]

print(rowsums, last_two_rows)

0      88
1     122
2     113
3      85
4      97
     ...
10     62
11     90
12     88
13    114
14    130
Length: 15, dtype: int64      0   1   2   3
13  26  26  36  26
14  30  28  33  39